### ISSUE TITLE
Missing demo data file

### ISSUE THREAD

**Issue by gangwu002** [jamesjcai/scGEAToolbox#16]
Hi James,

This is a great tool!  I tried to run the demos. One data file is missing for the following demos:
Demo 2, line 2: [X,genelist] =sc_readfile('example_data/GSM3044891_GeneExp.UMIs.10X1.txt');
Demo 3: line 4: [Z,genelistz]=sc_readfile('example_data/GSM3044891_GeneExp.UMIs.10X1.txt');
Demo 5: line 2: [X,genelist] =sc_readfile('example_data/GSM3044891_GeneExp.UMIs.10X1.txt');
Can you please add the data file? Thanks.

Gang Wu

**Comment by jamesjcai** [comment]
files are provided.
